import Link from 'next/link'
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container mx-auto pt-5'>
          <Link href="/" className='text-cyan-500 text-2xl font-semibold'>Podcaster</Link>
          <hr />
          {children}
        </div>
      </body>
    </html>
  )
}
